export const AUTH = {
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
};

export const LIST = {
  PURCHASES: "PURCHASES",
  PUBLICATIONS: "PUBLICATIONS",
};

export const FUNCTION_BTN = {
  VOLVER: "volver",
  FAVORITO: "favorito",
};

export const PUBLICATIONS = {
  ALL: "ALL",
  BY_CATEGORY: "BY_CATEGORY",
  BY_NAME: "BY_NAME",
};

export const PUBLICATION_ACTIONS = {
  SET_PUBLICATIONS: "SET_PUBLICATIONS",
  NEXT_PAGE: "NEXT_PAGE",
  PREV_PAGE: "PREV_PAGE",
  SET_TYPE: "SET_TYPE",
  SET_ID: "SET_ID",
  SET_SEARCH: "SET_SEARCH",
  RESET: "RESET",
};

export const DISCOUNTS_CODES = {
  CECCHIELMEJOR: "CECCHIELMEJOR",
};
